# Project information
site_name: SeleniumBase | Docs
site_url: https://seleniumbase.io
site_author: Michael Mintz
site_description: Reliable Browser Automation & Testing
# Repository information
repo_name: seleniumbase/SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase
edit_uri: ""
site_dir: "site"
docs_dir: "docs"
# Copyright
copyright: Copyright &copy; 2016 - 2020 Michael Mintz / SeleniumBase
# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
# Configuration
theme:
  name: material
  logo: img/logo3a.png
  favicon: img/logo3a.png
  include_homepage_in_sidebar: true
  sticky_navigation: true
  language: en
  include_search_page: false
  search_index_only: true
  features:
    - tabs
    - instant
  palette:
    scheme: default
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: img/sb_logo_7.png
# Plugins
plugins:
  - search
  - minify:
      minify_html: false
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: docs.prepare:main
# Page tree
nav:
  - SeleniumBase | Docs: README.md
  - Features: help_docs/features_list.md
  - CMD Options: help_docs/customizing_test_runs.md
  - Python Setup:
    - Install Python, pip, git: help_docs/install_python_pip_git.md
    - Virtualenv Instructions: help_docs/virtualenv_instructions.md
  - Installation:
    - Install SeleniumBase: help_docs/install.md
    - WebDriver Installation: help_docs/webdriver_installation.md
    - Verifying WebDriver: help_docs/verify_webdriver.md
    - How it Works: help_docs/how_it_works.md
  - Examples: examples/ReadMe.md
  - API Reference: help_docs/method_summary.md
  - Languages / 语言:
    - Translations: help_docs/translations.md
    - Chinese / 中文文件: help_docs/chinese.md
  - Mobile Testing: help_docs/mobile_testing.md
  - Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - JS Package Manager: help_docs/js_package_manager.md
  - Site Tours: examples/tour_examples/ReadMe.md
  - Visual Testing: examples/visual_testing/ReadMe.md
  - Integrations:
    - Logging and Reports: examples/example_logs/ReadMe.md
    - GitHub CI: integrations/github/workflows/ReadMe.md
    - Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md
    - Katalon Recorder: integrations/katalon/ReadMe.md
    - MasterQA: examples/master_qa/ReadMe.md
    - MySQL Help: help_docs/mysql_installation.md
    - Jenkins on Azure: integrations/azure/jenkins/ReadMe.md
    - Jenkins on Google Cloud: integrations/google_cloud/ReadMe.md
    - Docker Help: integrations/docker/ReadMe.md
    - Recorder and Exporting: seleniumbase/utilities/selenium_ide/ReadMe.md
  - Help Docs ToC:
    - Table of Contents: help_docs/ReadMe.md
    - Master QA: seleniumbase/masterqa/ReadMe.md
    - Decorators & Security: seleniumbase/common/ReadMe.md
    - Desired Capabilities: help_docs/desired_capabilities.md
    - Using Safari Driver: help_docs/using_safari_driver.md
    - macOS Hidden Files: help_docs/hidden_files_info.md
    - Case Studies: help_docs/happy_customers.md
  - Demo Page for Tests: https://seleniumbase.io/demo_page
  - Thank You: help_docs/thank_you.md
# Google Analytics
google_analytics: ['UA-167313767-1', 'seleniumbase.io']